/** Generic data helpers and secure CRUD. */
function masterEntitySheet_(entity) { const key=String(entity||'').trim().toUpperCase(); const sheetName=MASTER_SHEETS[key]; if(!sheetName) throw new Error('UNKNOWN_ENTITY'); return sheetName; }
function serializableValue_(value) { if(value instanceof Date) return Utilities.formatDate(value,Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM-dd HH:mm:ss'); if(value===null||value===undefined)return ''; return value; }
function sanitizeClientRow_(sheetName,data){const row={};Object.keys(data||{}).forEach(k=>{if(sheetName===MASTER_SHEETS.USERS&&k==='password_hash')return;row[k]=serializableValue_(data[k]);});return row;}
function sanitizeAuditPayload_(sheetName,data){return sanitizeClientRow_(sheetName,data);}
function getAdminClass_(user){const cls=readObjects_(MASTER_SHEETS.KELAS).find(k=>String(k.id)===String(user.kelas_id));if(!cls)throw new Error('KELAS_NOT_FOUND');return cls;}
function getMasterRows(entity){const user=requireAuth_(),sheetName=masterEntitySheet_(entity);if(user.role!==ROLE.OWNER&&sheetName!==MASTER_SHEETS.SISWA)throw new Error('FORBIDDEN');let rows=readObjects_(sheetName).map(r=>sanitizeClientRow_(sheetName,r));if(user.role===ROLE.ADMIN_KELAS&&sheetName===MASTER_SHEETS.SISWA){const cls=getAdminClass_(user);rows=rows.filter(r=>String(r.kelas_id)===String(cls.kode));}return rows;}
function getUserRelationOptions(){requireOwner_();return{guru:readObjects_(MASTER_SHEETS.GURU).filter(r=>String(r.status||'AKTIF').toUpperCase()!=='NONAKTIF').map(sanitizeClientRow_.bind(null,MASTER_SHEETS.GURU)),karyawan:readObjects_(MASTER_SHEETS.KARYAWAN).filter(r=>String(r.status||'AKTIF').toUpperCase()!=='NONAKTIF').map(sanitizeClientRow_.bind(null,MASTER_SHEETS.KARYAWAN)),siswa:readObjects_(MASTER_SHEETS.SISWA).filter(r=>String(r.status||'AKTIF').toUpperCase()!=='NONAKTIF').map(sanitizeClientRow_.bind(null,MASTER_SHEETS.SISWA)),kelas:readObjects_(MASTER_SHEETS.KELAS).filter(r=>String(r.status||'AKTIF').toUpperCase()!=='NONAKTIF').map(sanitizeClientRow_.bind(null,MASTER_SHEETS.KELAS))};}
function findMasterById_(sheetName,id){if(!id)return null;return readObjects_(sheetName).find(r=>String(r.id)===String(id))||null;}
function validateUserRelation_(data,existingId){const role=String(data.role||'').toUpperCase(),allUsers=readObjects_(MASTER_SHEETS.USERS),linked=allUsers.filter(u=>String(u.id)!==String(existingId||'')&&String(u.status||'AKTIF').toUpperCase()!=='NONAKTIF');if(role===ROLE.OWNER){data.guru_id='';data.karyawan_id='';data.siswa_id='';data.kelas_id='';return data;}if(role===ROLE.GURU){if(!data.guru_id)throw new Error('GURU_REQUIRED');const guru=findMasterById_(MASTER_SHEETS.GURU,data.guru_id);if(!guru)throw new Error('GURU_NOT_FOUND');if(linked.some(u=>String(u.guru_id)===String(data.guru_id)))throw new Error('GURU_ALREADY_HAS_USER');data.nama=String(guru.nama||'').trim();data.karyawan_id='';data.siswa_id='';data.kelas_id='';return data;}if(role===ROLE.KARYAWAN){if(!data.karyawan_id)throw new Error('KARYAWAN_REQUIRED');const k=findMasterById_(MASTER_SHEETS.KARYAWAN,data.karyawan_id);if(!k)throw new Error('KARYAWAN_NOT_FOUND');if(linked.some(u=>String(u.karyawan_id)===String(data.karyawan_id)))throw new Error('KARYAWAN_ALREADY_HAS_USER');data.nama=String(k.nama||'').trim();data.guru_id='';data.siswa_id='';data.kelas_id='';return data;}if(role===ROLE.SISWA){if(!data.siswa_id)throw new Error('SISWA_REQUIRED');const s=findMasterById_(MASTER_SHEETS.SISWA,data.siswa_id);if(!s)throw new Error('SISWA_NOT_FOUND');if(linked.some(u=>String(u.siswa_id)===String(data.siswa_id)))throw new Error('SISWA_ALREADY_HAS_USER');data.nama=String(s.nama||'').trim();data.kelas_id=String(s.kelas_id||'');data.guru_id='';data.karyawan_id='';return data;}if(role===ROLE.ADMIN_KELAS){if(!data.kelas_id)throw new Error('KELAS_REQUIRED');const kelas=findMasterById_(MASTER_SHEETS.KELAS,data.kelas_id);if(!kelas)throw new Error('KELAS_NOT_FOUND');if(linked.some(u=>String(u.kelas_id)===String(data.kelas_id)&&String(u.role).toUpperCase()===ROLE.ADMIN_KELAS))throw new Error('KELAS_ALREADY_HAS_ADMIN');data.nama=String(data.nama||kelas.nama||'').trim();data.guru_id='';data.karyawan_id='';data.siswa_id='';return data;}throw new Error('INVALID_ROLE');}
function saveMasterRow(entity,data){const user=requireAuth_(),sheetName=masterEntitySheet_(entity);if(user.role!==ROLE.OWNER&&sheetName!==MASTER_SHEETS.SISWA)throw new Error('FORBIDDEN');if(!data||typeof data!=='object')throw new Error('INVALID_DATA');data=Object.assign({},data);if(user.role===ROLE.ADMIN_KELAS&&sheetName===MASTER_SHEETS.SISWA){const cls=getAdminClass_(user);data.kelas_id=String(cls.kode||'');if(!data.kelas_id)throw new Error('CLASS_SCOPE_MISSING');if(data.id){const existing=readObjects_(MASTER_SHEETS.SISWA).find(r=>String(r.id)===String(data.id));if(!existing||String(existing.kelas_id)!==String(cls.kode))throw new Error('FORBIDDEN');}}
if(sheetName===MASTER_SHEETS.USERS){data.username=String(data.username||'').trim().toLowerCase();data.role=String(data.role||'').trim().toUpperCase();data.status=String(data.status||'AKTIF').trim().toUpperCase();if(!data.username||!data.role)throw new Error('USERNAME_ROLE_REQUIRED');if(!Object.keys(ROLE).map(k=>ROLE[k]).includes(data.role))throw new Error('INVALID_ROLE');const duplicate=readObjects_(sheetName).find(r=>String(r.username||'').trim().toLowerCase()===data.username&&String(r.id)!==String(data.id||''));if(duplicate)throw new Error('USERNAME_ALREADY_EXISTS');data=validateUserRelation_(data,data.id);delete data.password_hash;}
const now=new Date();data.updated_at=now;if(!data.id){data.id=Utilities.getUuid();data.created_at=now;if(sheetName===MASTER_SHEETS.USERS){const password=String(data.password||'');if(password.length<5)throw new Error('PASSWORD_MIN_5');data.password_hash=hashPassword_(password);delete data.password;}const sheet=getMasterSpreadsheet_().getSheetByName(sheetName);if(!sheet)throw new Error('SHEET_NOT_FOUND');appendObject_(sheet,data);}else{if(sheetName===MASTER_SHEETS.USERS&&Object.prototype.hasOwnProperty.call(data,'password')){const password=String(data.password||'');if(password&&password.length<5)throw new Error('PASSWORD_MIN_5');if(password)data.password_hash=hashPassword_(password);}delete data.password;updateById_(sheetName,data.id,data);}
if(sheetName===MASTER_SHEETS.KELAS){if(!String(data.sheet_name||'').trim())data.sheet_name=makeClassSheetName_(data.kode,data.nama);data.sheet_name=normalizeSheetName_(data.sheet_name);const actualName=createOrEnsureClassSheet_(data);data.sheet_name=actualName;updateById_(sheetName,data.id,{sheet_name:actualName,updated_at:new Date()});}audit_(user,'SAVE',sheetName,data.id,sanitizeAuditPayload_(sheetName,data));return{ok:true,row:sanitizeClientRow_(sheetName,data)};}
function deleteMasterRow(entity,id){const user=requireOwner_(),sheetName=masterEntitySheet_(entity);if(!id)throw new Error('INVALID_DELETE_REQUEST');deleteById_(sheetName,id);audit_(user,'DELETE',sheetName,id,{});return{ok:true};}
function readObjects_(sheetName){const sh=getMasterSpreadsheet_().getSheetByName(sheetName);if(!sh||sh.getLastRow()<2||sh.getLastColumn()<1)return[];const values=sh.getRange(1,1,sh.getLastRow(),sh.getLastColumn()).getValues(),headers=(values[0]||[]).map(parseColumnId_);return values.slice(1).filter(row=>row.some(v=>v!==''&&v!=null)).map(row=>{const o={};headers.forEach((h,i)=>{if(h)o[h]=row[i]});return o;});}
function appendObject_(sheet,obj){if(!sheet)throw new Error('SHEET_NOT_FOUND');const headers=(sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),1)).getValues()[0]||[]).map(parseColumnId_);if(!headers.length)throw new Error('HEADER_NOT_FOUND');sheet.appendRow(headers.map(h=>obj[h]==null?'':obj[h]));}
function updateById_(sheetName,id,data){const sh=getMasterSpreadsheet_().getSheetByName(sheetName);if(!sh||sh.getLastRow()<2)throw new Error('ROW_NOT_FOUND');const vals=sh.getRange(1,1,sh.getLastRow(),sh.getLastColumn()).getValues(),headers=vals[0].map(parseColumnId_),idCol=headers.indexOf('id');if(idCol<0)throw new Error('ID_COLUMN_MISSING');const rowIdx=vals.findIndex((r,i)=>i>0&&String(r[idCol])===String(id));if(rowIdx===-1)throw new Error('ROW_NOT_FOUND');Object.keys(data||{}).forEach(k=>{const c=headers.indexOf(k);if(c>=0)sh.getRange(rowIdx+1,c+1).setValue(data[k]);});}
function deleteById_(sheetName,id){const sh=getMasterSpreadsheet_().getSheetByName(sheetName);if(!sh||sh.getLastRow()<2)throw new Error('ROW_NOT_FOUND');const vals=sh.getRange(1,1,sh.getLastRow(),Math.max(sh.getLastColumn(),1)).getValues(),headers=vals[0].map(parseColumnId_),idCol=headers.indexOf('id');if(idCol<0)throw new Error('ID_COLUMN_MISSING');const idx=vals.findIndex((r,i)=>i>0&&String(r[idCol])===String(id));if(idx<0)throw new Error('ROW_NOT_FOUND');sh.deleteRow(idx+1);}
function makeClassSheetName_(kode,nama){const base=String(kode||nama||'KELAS').trim().toUpperCase(),clean=base.replace(/[^A-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').substring(0,70);return normalizeSheetName_('KELAS_'+(clean||Utilities.getUuid().slice(0,8)));}
function normalizeSheetName_(name){let s=String(name||'').trim().replace(/[\\/?*\[\]:]/g,'_');s=s.substring(0,90).trim();if(!s)throw new Error('INVALID_SHEET_NAME');return s;}
function audit_(user,action,target,targetId,payload){try{appendObject_(getMasterSpreadsheet_().getSheetByName(MASTER_SHEETS.AUDIT),{id:Utilities.getUuid(),actor_user_id:user.id,action,target,target_id:targetId,payload_json:JSON.stringify(payload||{}),created_at:new Date()});}catch(e){}}
